name: Generate WebDev Hype Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytrends matplotlib

      - name: Fetch latest changes from GitHub
        run: git fetch origin main

      - name: Rebase local changes on top of fetched changes
        run: git rebase origin/main

      - name: Generate Graph
        run: python main.py

      - name: Configure Git and Push Changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Generated webdev-data graph"
          git push
